In [12]:
import jax
import jax.numpy as jnp
import pandas as pd
from sklearn.impute import KNNImputer

## EDA / Bare Minimum Feature Engineering

In [13]:
training_data = pd.read_csv ('data/train.csv')
training_data.describe

<bound method NDFrame.describe of         Id                                  industry             sector  \
0      196                         Personal Services  Consumer Cyclical
1     1568             Building Products & Equipment        Industrials
2     1218                                       NaN            Unknown
3       23        Scientific & Technical Instruments         Technology
4      783  Drug Manufacturers - Specialty & Generic         Healthcare
...    ...                                       ...                ...
1619  1916                Engineering & Construction        Industrials
1620  1162                             Biotechnology         Healthcare
1621   629                   Medical Care Facilities         Healthcare
1622  1841                             Biotechnology         Healthcare
1623  1179                         Resorts & Casinos  Consumer Cyclical

      fullTimeEmployees  auditRisk  boardRisk  compensationRisk  \
0                1174.0        5.0       10.0               9.0
1                3600.0        4.0        4.0               3.0
2                   NaN        NaN        NaN               NaN
3                 143.0        NaN        NaN               NaN
4                  36.0        NaN        NaN               NaN
...                 ...        ...        ...               ...
1619             1600.0        8.0        8.0               6.0
1620               70.0        2.0        7.0               6.0
1621             5335.0        8.0        7.0               6.0
1622              129.0        7.0        6.0               8.0
1623            27000.0        8.0        3.0              10.0

      shareHolderRightsRisk  overallRisk   trailingPE  ...  \
0                       4.0          8.0    12.549223  ...
1                       4.0          3.0  1222.000000  ...
2                       NaN          NaN          NaN  ...
3                       NaN          NaN          NaN  ...
4                       NaN          NaN     1.231544  ...
...                     ...          ...          ...  ...
1619                    8.0          7.0   310.800000  ...
1620                    2.0          4.0          NaN  ...
1621                    2.0          5.0    36.952385  ...
1622                    8.0          7.0          NaN  ...
1623                   10.0          9.0   336.750000  ...

      Q10_TOTAL_STOCKHOLDERS_EQUITY  Q10_NET_INCOME  Q10_GROSS_PROFIT  \
0                      2.405020e+08             NaN      2.317100e+07
1                      3.265380e+08     -71929000.0      4.105740e+08
2                      4.066300e+10     603000000.0      1.649000e+09
3                      2.758000e+03         -9715.0      0.000000e+00
4                      2.592400e+07      -4676000.0      1.205000e+07
...                             ...             ...               ...
1619                   1.838300e+07        981000.0      1.564600e+07
1620                   1.176740e+08      -1416000.0      2.790000e+05
1621                   3.226923e+08        950000.0      2.204100e+07
1622                   9.164100e+07     -16514000.0      1.222000e+06
1623                   2.336830e+08    -280978000.0      1.642520e+08

      Q10_COST_OF_REVENUES  Q10_REVENUES  Q10_OPERATING_INCOME  \
0             5.431900e+07  4.073200e+07             2150000.0
1             6.926880e+08  1.103262e+09           -39287000.0
2             4.587000e+09  6.236000e+09           663000000.0
3                      NaN           NaN               -9683.0
4             0.000000e+00  1.205000e+07            -1594000.0
...                    ...           ...                   ...
1619          1.615600e+07  3.180200e+07             1495000.0
1620          1.120000e+05  3.910000e+05            -7050000.0
1621          8.362200e+07  1.056630e+08             1613000.0
1622          0.000000e+00  1.222000e+06           -16561000.0
1623          3.519660e+08  5.162180e+08          -175732000.0

      Q10_OPERATING_EXPENSES    Q10_EBITDA  Q10_DEPRECIATION_AND_AMORTIZATION  \
0                  5946000.0  1.722500e+07                         15075000.0
1                333229000.0  7.734500e+07                        116632000.0
2                214000000.0  1.435000e+09                        772000000.0
3                     9683.0 -9.683000e+03                                0.0
4                 13644000.0 -1.594000e+06                                0.0
...                      ...           ...                                ...
1619              14151000.0  1.495000e+06                                0.0
1620               7329000.0 -7.050000e+06                                0.0
1621             104050000.0 -8.200900e+07                        -83622000.0
1622              17783000.0 -1.656100e+07                                0.0
1623             179774000.0 -1.552200e+07                        160210000.0

      Q10_fiscal_year_end
0                     0.0
1                     0.0
2                     0.0
3                     0.0
4                     0.0
...                   ...
1619                  0.0
1620                  0.0
1621                  0.0
1622                  0.0
1623                  0.0

[1624 rows x 212 columns]>

In [14]:
training_data.dtypes
training_data.head(5)

,Id,industry,sector,fullTimeEmployees,auditRisk,boardRisk,compensationRisk,shareHolderRightsRisk,overallRisk,trailingPE,...,Q10_TOTAL_STOCKHOLDERS_EQUITY,Q10_NET_INCOME,Q10_GROSS_PROFIT,Q10_COST_OF_REVENUES,Q10_REVENUES,Q10_OPERATING_INCOME,Q10_OPERATING_EXPENSES,Q10_EBITDA,Q10_DEPRECIATION_AND_AMORTIZATION,Q10_fiscal_year_end
0,196,Personal Services,Consumer Cyclical,1174.0,5.0,10.0,9.0,4.0,8.0,12.549223,...,2.405020e+08,NaN,2.317100e+07,5.431900e+07,4.073200e+07,2150000.0,5946000.0,1.722500e+07,15075000.0,0.0
1,1568,Building Products & Equipment,Industrials,3600.0,4.0,4.0,3.0,4.0,3.0,1222.000000,...,3.265380e+08,-71929000.0,4.105740e+08,6.926880e+08,1.103262e+09,-39287000.0,333229000.0,7.734500e+07,116632000.0,0.0
2,1218,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.066300e+10,603000000.0,1.649000e+09,4.587000e+09,6.236000e+09,663000000.0,214000000.0,1.435000e+09,772000000.0,0.0
3,23,Scientific & Technical Instruments,Technology,143.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2.758000e+03,-9715.0,0.000000e+00,NaN,NaN,-9683.0,9683.0,-9.683000e+03,0.0,0.0
4,783,Drug Manufacturers - Specialty & Generic,Healthcare,36.0,NaN,NaN,NaN,NaN,NaN,1.231544,...,2.592400e+07,-4676000.0,1.205000e+07,0.000000e+00,1.205000e+07,-1594000.0,13644000.0,-1.594000e+06,0.0,0.0

In [15]:
training_data_dummies = pd.get_dummies(training_data, columns=['industry', 'sector'])
training_data_dummies.head(5)

,Id,fullTimeEmployees,auditRisk,boardRisk,compensationRisk,shareHolderRightsRisk,overallRisk,trailingPE,forwardPE,floatShares,...,sector_Basic Materials,sector_Communication Services,sector_Consumer Cyclical,sector_Consumer Defensive,sector_Energy,sector_Healthcare,sector_Industrials,sector_Technology,sector_Unknown,sector_Utilities
0,196,1174.0,5.0,10.0,9.0,4.0,8.0,12.549223,10.530435,13278816.0,...,False,False,True,False,False,False,False,False,False,False
1,1568,3600.0,4.0,4.0,3.0,4.0,3.0,1222.000000,13.730337,56524722.0,...,False,False,False,False,False,False,True,False,False,False
2,1218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,True,False
3,23,143.0,NaN,NaN,NaN,NaN,NaN,NaN,-1.226667,4951058.0,...,False,False,False,False,False,False,False,True,False,False
4,783,36.0,NaN,NaN,NaN,NaN,NaN,1.231544,7.340000,33971093.0,...,False,False,False,False,False,True,False,False,False,False

In [16]:
##check nan count for each columns
nan_counts = training_data_dummies.isna().sum()
print(nan_counts)

Id                      0
fullTimeEmployees      80
auditRisk             493
boardRisk             493
compensationRisk      493
                     ...
sector_Healthcare       0
sector_Industrials      0
sector_Technology       0
sector_Unknown          0
sector_Utilities        0
Length: 333, dtype: int64